version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "${WEB_EXTERNAL_PORT:-3000}:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-CHANGE_THIS_TO_A_SECURE_RANDOM_STRING_GENERATE_WITH_OPENSSL}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:ServerDash2024!@db:5432/serverdash}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - NOTIFICATIONS_ENABLED=${NOTIFICATIONS_ENABLED:-true}
      - EMAIL_NOTIFICATIONS=${EMAIL_NOTIFICATIONS:-true}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - ENABLE_REGISTRATION=${ENABLE_REGISTRATION:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - ENABLE_SECURITY_HEADERS=${ENABLE_SECURITY_HEADERS:-true}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL:-}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ServerDash2024!}
      - POSTGRES_DB=${POSTGRES_DB:-serverdash}
    depends_on:
      - db
    restart: unless-stopped

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile.local
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:ServerDash2024!@db:5432/serverdash}
      - SERVER_CHECK_INTERVAL=${SERVER_CHECK_INTERVAL:-30}
      - NETWORK_CHECK_INTERVAL=${NETWORK_CHECK_INTERVAL:-45}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ServerDash2024!}
      - POSTGRES_DB=${POSTGRES_DB:-serverdash}
    depends_on:
      - db
    restart: unless-stopped

  uptime:
    build:
      context: .
      dockerfile: Dockerfile.uptime
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:ServerDash2024!@db:5432/serverdash}
      - UPTIME_CHECK_INTERVAL=${UPTIME_CHECK_INTERVAL:-60}
      - NOTIFICATIONS_ENABLED=${NOTIFICATIONS_ENABLED:-true}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ServerDash2024!}
      - POSTGRES_DB=${POSTGRES_DB:-serverdash}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ServerDash2024!}
      - POSTGRES_DB=${POSTGRES_DB:-serverdash}
    ports:
      - "${DB_EXTERNAL_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
